### PR TITLE
feat: added hamburger menu and some UI changes

### PR DESCRIPTION
**Pull request by zabihhaqqani**
added a responsive menu and made some UI changes

### CODE REVIEW

**Comment by hasnainabeel** [comment]
thanks for contributing @zabihhaqqani

**Comment by hasnainabeel** [comment]
Thanks for contributing @zabihhaqqani 
Make the following change:
    ‣Remove the padding for main-header in the media.
    ‣Add hamburger section in all the .HTML files in 'x-year-branch'.

**Comment by zabihhaqqani** [comment]
Sure will do the changes !

**Comment by zabihhaqqani** [comment]
I have done the necessary changes and made a new PR.

**Pull request closed without merging**
